{"name": "Ошибка при неверном пароле", "status": "passed", "description": "Проверка ошибки 404 при неправильном пароле", "steps": [{"name": "Отправка запроса авторизации с неверным паролем", "status": "passed", "start": 1752420311037, "stop": 1752420311280}, {"name": "Проверка, что возвращается ошибка 404", "status": "passed", "start": 1752420311280, "stop": 1752420311280}], "start": 1752420311037, "stop": 1752420311280, "uuid": "3e4385e3-b167-4f46-9714-d8a2e080d7b9", "historyId": "aa888bf6591480a9eed6507c8477d338", "testCaseId": "aa888bf6591480a9eed6507c8477d338", "fullName": "Tests.test_login_courier.TestLoginCourier#test_login_with_error_in_password", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-T2S04D8"}, {"name": "thread", "value": "8088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login_courier"}]}