{"name": "Ошибка при неверном id курьера", "status": "passed", "description": "Проверка ошибки 404 при использовании несуществующего id курьера", "steps": [{"name": "Отправка запроса на принятие заказа с id_order=505650 и некорректным id_courier=123123123", "status": "passed", "start": 1752420294561, "stop": 1752420294817}, {"name": "Проверка, что статус ответа равен 404", "status": "passed", "start": 1752420294817, "stop": 1752420294817}], "attachments": [{"name": "log", "source": "8e8e95d4-48ce-4d7f-9cda-a786faad9bdf-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "e2902268-95d6-4db2-a959-f5ebb915b3c4-attachment.txt", "type": "text/plain"}], "start": 1752420294561, "stop": 1752420294817, "uuid": "79ba3a3a-5d9e-47db-a336-c9cdcf275c4a", "historyId": "bb4df49adc39dc05d4c67c4d62edfb84", "testCaseId": "bb4df49adc39dc05d4c67c4d62edfb84", "fullName": "Tests.test_accept_order.TestAcceptOrder#test_accept_order_with_wrong_id_courier", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "DESKTOP-T2S04D8"}, {"name": "thread", "value": "8088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_accept_order"}]}