{"name": "Удаление без ID", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидалось сообщение {'message': 'Недостаточно данных для удаления курьера'}, получено: {'code': 404, 'message': 'Not Found.'}\nassert {'code': 404,... 'Not Found.'} == {'message': '...ения курьера'}\n  \n  Differing items:\n  \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mmessage\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[33m'\u001b[39;49;00m\u001b[33mNot Found.\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m != \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mmessage\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[33m'\u001b[39;49;00m\u001b[33mНедостаточно данных для удаления курьера\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\n  Left contains 1 more item:\n  \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mcode\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[94m404\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\n  Use -v to get more diff", "trace": "self = <Tests.test_delete_courier.TestDeleteCourier object at 0x0000020E93CD6FD0>\n\n    @allure.title(\"Удаление без ID\")\n    @allure.description(\"Проверка текста ошибки при удалении курьера без указания id.\")\n    def test_text_after_delete_without_id(self):\n        with allure.step(\"Отправка запроса на удаление без указания id\"):\n            response = requests.delete(f\"{BASE_URL}/courier/\")\n    \n        with allure.step(\"Проверка текста ошибки в ответе\"):\n            expected = {\"message\": \"Недостаточно данных для удаления курьера\"}\n>           assert response.json() == expected, f\"Ожидалось сообщение {expected}, получено: {response.json()}\"\nE           AssertionError: Ожидалось сообщение {'message': 'Недостаточно данных для удаления курьера'}, получено: {'code': 404, 'message': 'Not Found.'}\nE           assert {'code': 404,... 'Not Found.'} == {'message': '...ения курьера'}\nE             \nE             Differing items:\nE             \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mmessage\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[33m'\u001b[39;49;00m\u001b[33mNot Found.\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m != \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mmessage\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[33m'\u001b[39;49;00m\u001b[33mНедостаточно данных для удаления курьера\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\nE             Left contains 1 more item:\nE             \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mcode\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[94m404\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\nE             Use -v to get more diff\n\nTests\\test_delete_courier.py:28: AssertionError"}, "description": "Проверка текста ошибки при удалении курьера без указания id.", "steps": [{"name": "Отправка запроса на удаление без указания id", "status": "passed", "start": 1752420302451, "stop": 1752420302701}, {"name": "Проверка текста ошибки в ответе", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидалось сообщение {'message': 'Недостаточно данных для удаления курьера'}, получено: {'code': 404, 'message': 'Not Found.'}\nassert {'code': 404,... 'Not Found.'} == {'message': '...ения курьера'}\n  \n  Differing items:\n  \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mmessage\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[33m'\u001b[39;49;00m\u001b[33mNot Found.\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m != \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mmessage\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[33m'\u001b[39;49;00m\u001b[33mНедостаточно данных для удаления курьера\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\n  Left contains 1 more item:\n  \u001b[0m{\u001b[33m'\u001b[39;49;00m\u001b[33mcode\u001b[39;49;00m\u001b[33m'\u001b[39;49;00m: \u001b[94m404\u001b[39;49;00m}\u001b[90m\u001b[39;49;00m\n  Use -v to get more diff\n", "trace": "  File \"C:\\Users\\ikhri\\Documents\\GitHub\\qa_python_7_sprint\\Tests\\test_delete_courier.py\", line 28, in test_text_after_delete_without_id\n    assert response.json() == expected, f\"Ожидалось сообщение {expected}, получено: {response.json()}\"\n"}, "start": 1752420302701, "stop": 1752420302701}], "start": 1752420302451, "stop": 1752420302702, "uuid": "519239e4-8174-455c-bf4b-22de4ce256f3", "historyId": "5e5a2b2aba6c6ce9dd52c7abd9455751", "testCaseId": "5e5a2b2aba6c6ce9dd52c7abd9455751", "fullName": "Tests.test_delete_courier.TestDeleteCourier#test_text_after_delete_without_id", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_delete_courier"}, {"name": "subSuite", "value": "TestDeleteCourier"}, {"name": "host", "value": "DESKTOP-T2S04D8"}, {"name": "thread", "value": "8088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_delete_courier"}]}